-- MySQL Script generated by MySQL Workbench
-- Fri Jan 24 13:36:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema etudiants
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema etudiants
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `etudiants` DEFAULT CHARACTER SET latin1 ;
USE `etudiants` ;

-- -----------------------------------------------------
-- Table `etudiants`.`programmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etudiants`.`programmes` (
  `noProgramme` VARCHAR(10) NOT NULL,
  `nomProgramme` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`noProgramme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `etudiants`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etudiants`.`cours` (
  `noCours` VARCHAR(10) NOT NULL,
  `nomCours` VARCHAR(100) NOT NULL,
  `nbHeure` INT(11) NOT NULL,
  `noProgramme` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`noCours`),
  INDEX `FkCoursProgramme` (`noProgramme` ASC) VISIBLE,
  INDEX `idxNomCours` (`nomCours` ASC) VISIBLE,
  CONSTRAINT `FkCoursProgramme`
    FOREIGN KEY (`noProgramme`)
    REFERENCES `etudiants`.`programmes` (`noProgramme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `etudiants`.`etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etudiants`.`etudiants` (
  `noEtudiant` VARCHAR(15) NOT NULL,
  `nomEtudiant` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `noProgramme` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`noEtudiant`),
  INDEX `FkEtudiants_Programme` (`noProgramme` ASC) VISIBLE,
  INDEX `idxNomLong` (`nomEtudiant` ASC, `prenom` ASC) VISIBLE,
  CONSTRAINT `FkEtudiants_Programme`
    FOREIGN KEY (`noProgramme`)
    REFERENCES `etudiants`.`programmes` (`noProgramme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
